monitor.alsa.rules = [
  {
    # === OUTPUT ===
    matches = [
      { node.name = "alsa_output.platform-sound.HiFi__Speaker__sink" }
    ]
    actions = {
      update-props = {
        audio.format     = "S16LE"
        audio.rate       = 48000
        audio.channels   = 2
        audio.position   = [ "FL" "FR" ]
        api.alsa.soft-mixer  = true
        api.alsa.period-size = 2048
        api.alsa.period-num  = 8
        api.alsa.headroom    = 4096
        channelmix.max-volume = 0.88
      }
    }
  },
  {
    # === INPUT ===
    matches = [
      { node.name = "alsa_input.platform-sound.HiFi__Mic__source" }
    ]
    actions = {
      update-props = {
        audio.format     = "S16LE"
        audio.rate       = 44100
        audio.channels   = 2
        audio.position   = [ "FL" "FR" ]
        api.alsa.period-size = 1024
        api.alsa.period-num  = 4
      }
    }
  }
]
