monitor.libcamera.rules = [
  {
    matches = [
      { node.name = "~libcamera_input.*camera_10" }
    ]
    actions = {
      update-props = {
        video.size = { width = 1920, height = 1080 }
      }
    }
  },
  {
    matches = [
      { node.name = "~libcamera_input.*camera_20" }
    ]
    actions = {
      update-props = {
        video.size = { width = 1280, height = 720 }
      }
    }
  }
]
