#!/bin/sh
set -eu

for dir in \
    /mnt/vendor \
    /mnt/vendor/persist \
    /mnt/vendor/persist/sensors \
    /mnt/vendor/persist/sensors/registry \
    /mnt/vendor/persist/sensors/registry/registry
do
    install -d -m 0775 -o fastrpc -g fastrpc "$dir"
done

# hexagonrpcd tries to write to ../temp.json
# Ensure the parent directory is writable by fastrpc
chown fastrpc:fastrpc /mnt/vendor/persist/sensors/registry
chmod 0775 /mnt/vendor/persist/sensors/registry
