post_install() {
  systemd-tmpfiles --create /usr/lib/tmpfiles.d/pipa-sensors.conf >/dev/null 2>&1 || true
  systemctl daemon-reload >/dev/null 2>&1 || true
  systemctl restart hexagonrpcd-adsp-rootpd.service >/dev/null 2>&1 || true
  systemctl restart hexagonrpcd-sdsp.service >/dev/null 2>&1 || true
  systemctl restart hexagonrpcd-adsp-sensorspd.service >/dev/null 2>&1 || true
  systemctl restart iio-sensor-proxy.service >/dev/null 2>&1 || true
}

post_upgrade() {
  post_install "$@"
}
