monitor.alsa.rules = [
  {
    #region debug-point A:D:device-rule-match
    matches = [
      { device.name = "alsa_card.platform-sound" }
    ]
    actions = {
      update-props = {
        device.nick = "Pipa Audio [dbg-audio-crackle]"
        debug.pipa.device-rule = "hit"
      }
    }
    #endregion debug-point A:D:device-rule-match
  },
  {
    # === OUTPUT ===
    #region debug-point A:D:output-rule-match
    matches = [
      { node.name = "alsa_output.platform-sound.HiFi__Speaker__sink" }
    ]
    actions = {
      update-props = {
        node.nick        = "Pipa Speaker [dbg-audio-crackle]"
        node.description = "Pipa Speaker [dbg-audio-crackle]"
        debug.pipa.output-rule = "hit"
        audio.format     = "S16LE"
        audio.rate       = 48000
        audio.channels   = 2
        audio.position   = [ "FL" "FR" ]
        api.alsa.soft-mixer = true
        api.alsa.period-size = 1024
        api.alsa.period-num  = 8
        api.alsa.headroom    = 2048
        api.alsa.disable-batch = true
      }
    }
    #endregion debug-point A:D:output-rule-match
  },
  {
    # === INPUT ===
    #region debug-point D:input-control-match
    matches = [
      { node.name = "alsa_input.platform-sound.HiFi__Mic__source" }
    ]
    actions = {
      update-props = {
        node.nick        = "Pipa Mic [dbg-audio-crackle]"
        node.description = "Pipa Mic [dbg-audio-crackle]"
        debug.pipa.input-rule = "hit"
        audio.format     = "S16LE"
        audio.rate       = 44100
        audio.channels   = 2
        audio.position   = [ "FL" "FR" ]
      }
    }
    #endregion debug-point D:input-control-match
  }
]
